/**
 * frontend/src/utils/kroneFleetData.ts
 * Authentic Krone Agriculture India Fleet, Technicians, Machines & Attendance Data Store.
 */

import { ExtendedTechnicianData } from '../components/TechnicianDetailView';

export const KRONE_FLEET_MASTER: ExtendedTechnicianData[] = [
  {
    id: 'TECH-01',
    name: 'Gurpreet Singh',
    role: 'Lead Baler Specialist',
    region: 'Punjab',
    phone: '+91 98140 88210',
    email: 'gurpreet.singh@krone.in',
    employeeCode: 'KIN-ENG-01',
    vehicleNumber: 'PB-10-CZ-4418',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:15 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Krone Regional Ag Depot Ludhiana Base',
    punchCoordinates: [30.9010, 75.8573],
    batteryLevel: 92,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26-0101',
    jobTitle: 'Knotter Timing Calibration & Twine Guide Replacement',
    customerCompany: 'Reliance Industries Limited (Bio-Energy Division)',
    machineName: 'Krone BigPack 1290 HDP High Density Baler',
    machineSerial: 'BP1290-78401',
    siteContact: 'Rajinder Verma (+91 98765 43210)',
    workingHours: 5.5,
    travelHours: 1.8,
    idleHours: 0.7,
    totalKm: 84.6,
    recentJobs: [
      { jobId: 'SR-26-0098', date: '2026-09-23', customer: 'Reliance Industries Ltd', machine: 'Krone BigPack 1290 HDP', status: 'Completed', type: 'Paid' },
      { jobId: 'SR-26-0091', date: '2026-09-21', customer: 'Punjab State Farm Coop', machine: 'Krone BigPack 1290 HDP', status: 'Completed', type: 'AMC' },
      { jobId: 'SR-26-0084', date: '2026-09-19', customer: 'Reliance Industries Ltd', machine: 'Krone Fortima V 1500', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-02',
    name: 'Vikram Sharma',
    role: 'Senior Service Engineer',
    region: 'Haryana',
    phone: '+91 98120 77412',
    email: 'vikram.sharma@krone.in',
    employeeCode: 'KIN-ENG-02',
    vehicleNumber: 'HR-20-AK-8812',
    vehicleModel: 'Mahindra Scorpio-N Utility',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:30 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Krone Service Station Hisar Hub',
    punchCoordinates: [29.1492, 75.7217],
    batteryLevel: 88,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26-0102',
    jobTitle: 'Bale Chamber Roller Bearing Service & Tension Calibration',
    customerCompany: 'Punjab State Farm Cooperative Hoshiarpur',
    machineName: 'Krone Bellima F 130 Round Baler',
    machineSerial: 'BL130-449120',
    siteContact: 'Sunil Kumar (Plant Head, +91 98123 99881)',
    workingHours: 4.8,
    travelHours: 2.1,
    idleHours: 0.6,
    totalKm: 112.4,
    recentJobs: [
      { jobId: 'SR-26-0095', date: '2026-09-22', customer: 'Haryana Kisan Agri Hub', machine: 'Krone Bellima F 130', status: 'Completed', type: 'Paid' },
      { jobId: 'SR-26-0089', date: '2026-09-20', customer: 'Adani Agri Logistics', machine: 'Krone Swadro TC 880', status: 'Completed', type: 'AMC' },
    ]
  },
  {
    id: 'TECH-03',
    name: 'Sunny Kumar',
    role: 'Lead Service Specialist',
    region: 'Haryana',
    phone: '+91 96259 57663',
    email: 'sunny.kumar@krone.in',
    employeeCode: 'KIN-ENG-03',
    vehicleNumber: 'HR-06-BB-3190',
    vehicleModel: 'Bolero Maxi Truck HD',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:20 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Panipat Service Point Base',
    punchCoordinates: [29.3909, 76.9635],
    batteryLevel: 95,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26-0103',
    jobTitle: '500-Hour Scheduled Preventive Maintenance & Knife Sharpening',
    customerCompany: 'VERBIO Bio-Gas India Pvt Ltd',
    machineName: 'Krone BiG X 680 Forage Harvester',
    machineSerial: 'BX6800-45912',
    siteContact: 'Harish Patel (+91 98221 44556)',
    workingHours: 5.2,
    travelHours: 1.5,
    idleHours: 0.8,
    totalKm: 68.2,
    recentJobs: [
      { jobId: 'SR-26-0096', date: '2026-09-23', customer: 'VERBIO Bio-Gas India', machine: 'Krone BiG X 680', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-04',
    name: 'Jaswinder Singh',
    role: 'Senior Field Specialist',
    region: 'Punjab',
    phone: '+91 98765 11223',
    email: 'jaswinder.singh@krone.in',
    employeeCode: 'KIN-ENG-04',
    vehicleNumber: 'PB-08-DJ-9012',
    vehicleModel: 'Tata Yodha 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:00 AM',
    clockOutTime: '05:00 PM (Est)',
    punchLocationName: 'Jalandhar Agri Cluster Depot',
    punchCoordinates: [31.3260, 75.5762],
    batteryLevel: 79,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26-0104',
    jobTitle: 'Bed Oil Leakage & Cutterbar Disc Inspection',
    customerCompany: 'SAEL Punjab Biomass Energy Project',
    machineName: 'Krone EasyCut B 870 Mower Conditioner',
    machineSerial: 'EC870-551029',
    siteContact: 'Maninderjit Singh (+91 98144 22331)',
    workingHours: 6.0,
    travelHours: 1.2,
    idleHours: 0.4,
    totalKm: 52.0,
    recentJobs: [
      { jobId: 'SR-26-0094', date: '2026-09-22', customer: 'SAEL Biomass', machine: 'Krone EasyCut B 870', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-05',
    name: 'B. Vignesh',
    role: 'Bio-Energy Field Specialist',
    region: 'Andhra Pradesh',
    phone: '+91 97037 19368',
    email: 'b.vignesh@krone.in',
    employeeCode: 'KIN-ENG-05',
    vehicleNumber: 'AP-26-TG-1102',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:10 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Nellore Bio-Gas Service Depot',
    punchCoordinates: [14.4426, 79.9865],
    batteryLevel: 91,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26-0105',
    jobTitle: 'Pre-Season Hydraulic Fluid Flush & Valve Pressure Testing',
    customerCompany: 'Reliance Industries Limited (Barabanki Bio-Fuels)',
    machineName: 'Krone BigPack 1290 HDP High Density Baler',
    machineSerial: 'BP1290-88214',
    siteContact: 'K. Venkatesh (+91 94405 67890)',
    workingHours: 5.8,
    travelHours: 1.6,
    idleHours: 0.5,
    totalKm: 78.5,
    recentJobs: [
      { jobId: 'SR-26-0092', date: '2026-09-21', customer: 'Reliance Industries Ltd', machine: 'Krone BigPack 1290 HDP', status: 'Completed', type: 'Paid' },
      { jobId: 'SR-26-0085', date: '2026-09-18', customer: 'Reliance Industries Ltd', machine: 'Krone BigPack 1290 HDP', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-06',
    name: 'M. Naveen Kumar',
    role: 'Field Service Engineer',
    region: 'Andhra Pradesh',
    phone: '+91 94401 22334',
    email: 'naveen.kumar@krone.in',
    employeeCode: 'KIN-ENG-06',
    vehicleNumber: 'AP-26-TG-1103',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:25 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Nellore Service Station Base',
    punchCoordinates: [14.4450, 79.9880],
    batteryLevel: 85,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26-0106',
    jobTitle: 'Flywheel Brake Lining Replacement & Slip Clutch Torquing',
    customerCompany: 'Godrej Agrovet Ltd Biomass Division',
    machineName: 'Krone BiG X 700 Forage Harvester',
    machineSerial: 'BX700-112045',
    siteContact: 'M. Subba Rao (+91 98480 33441)',
    workingHours: 5.4,
    travelHours: 1.9,
    idleHours: 0.7,
    totalKm: 95.0,
    recentJobs: [
      { jobId: 'SR-26-0097', date: '2026-09-23', customer: 'Godrej Agrovet Ltd', machine: 'Krone BiG X 700', status: 'Completed', type: 'Paid' },
      { jobId: 'SR-26-0088', date: '2026-09-20', customer: 'Reliance Industries Ltd', machine: 'Krone BigPack 1290 HDP', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-07',
    name: 'Palthiya Kishore',
    role: 'Field Service Engineer',
    region: 'Andhra Pradesh',
    phone: '+91 94402 33445',
    email: 'palthiya.kishore@krone.in',
    employeeCode: 'KIN-ENG-07',
    vehicleNumber: 'AP-26-KL-2201',
    vehicleModel: 'Tata Xenon Crew Cab',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:40 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Vijayawada Support Sub-Depot',
    punchCoordinates: [16.5062, 80.6480],
    batteryLevel: 94,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26-0107',
    jobTitle: 'Pickup Cam Track & Tine Bar Alignment',
    customerCompany: 'Adani Agri Logistics Ltd',
    machineName: 'Krone Swadro TC 880 Rake',
    machineSerial: 'SW880-662314',
    siteContact: 'P. Srinivas (+91 98491 55662)',
    workingHours: 4.5,
    travelHours: 2.3,
    idleHours: 0.8,
    totalKm: 120.0,
    recentJobs: [
      { jobId: 'SR-26-0093', date: '2026-09-21', customer: 'Adani Agri Logistics', machine: 'Krone Swadro TC 880', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-08',
    name: 'Nitin Gour',
    role: 'Field Technician',
    region: 'Madhya Pradesh',
    phone: '+91 98260 44556',
    email: 'nitin.gour@krone.in',
    employeeCode: 'KIN-ENG-08',
    vehicleNumber: 'MP-09-BC-6612',
    vehicleModel: 'Mahindra Bolero Pickup',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:15 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Indore Bio-Power Depot Base',
    punchCoordinates: [22.7196, 75.8577],
    batteryLevel: 87,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26-0108',
    jobTitle: 'Electronic Knotter Sensor Diagnostic & Wiring Harness Repair',
    customerCompany: 'ITC Paperboards Agri Forestry Division',
    machineName: 'Krone BigPack 1290 HDP High Density Baler',
    machineSerial: 'BP1290-78402',
    siteContact: 'Deepak Sharma (+91 98261 77882)',
    workingHours: 5.6,
    travelHours: 1.4,
    idleHours: 0.6,
    totalKm: 65.0,
    recentJobs: [
      { jobId: 'SR-26-0090', date: '2026-09-20', customer: 'ITC Paperboards', machine: 'Krone BigPack 1290 HDP', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-09',
    name: 'Sunil Kumar',
    role: 'Field Technician',
    region: 'Punjab',
    phone: '+91 98141 55667',
    email: 'sunil.kumar@krone.in',
    employeeCode: 'KIN-ENG-09',
    vehicleNumber: 'PB-10-EE-2201',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'Available',
    isPresent: true,
    clockInTime: '08:30 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Krone Regional Ag Depot Ludhiana Base',
    punchCoordinates: [30.9010, 75.8573],
    batteryLevel: 98,
    appVersion: 'Fieldy FSM v4.2.1',
    workingHours: 2.0,
    travelHours: 0.5,
    idleHours: 5.5,
    totalKm: 15.0,
    recentJobs: [
      { jobId: 'SR-26-0086', date: '2026-09-19', customer: 'Punjab State Farm Coop', machine: 'Krone Fortima V 1500', status: 'Completed', type: 'AMC' },
    ]
  },
  {
    id: 'TECH-10',
    name: 'Sachin Jadhav',
    role: 'Hydraulics Specialist',
    region: 'Maharashtra',
    phone: '+91 98220 66778',
    email: 'sachin.jadhav@krone.in',
    employeeCode: 'KIN-ENG-10',
    vehicleNumber: 'MH-12-PQ-8801',
    vehicleModel: 'Mahindra Scorpio Classic',
    status: 'Available',
    isPresent: true,
    clockInTime: '08:15 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Baramati Agro Hub Base',
    punchCoordinates: [18.1517, 74.5772],
    batteryLevel: 90,
    appVersion: 'Fieldy FSM v4.2.1',
    workingHours: 2.5,
    travelHours: 0.8,
    idleHours: 4.7,
    totalKm: 25.0,
    recentJobs: [
      { jobId: 'SR-26-0087', date: '2026-09-19', customer: 'Baramati Agro Clean Energy', machine: 'Krone BiG X 700', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-11',
    name: 'Vidhyant Kumar',
    role: 'Field Technician',
    region: 'Haryana',
    phone: '+91 98121 77889',
    email: 'vidhyant.kumar@krone.in',
    employeeCode: 'KIN-ENG-11',
    vehicleNumber: 'HR-20-MM-3344',
    vehicleModel: 'Bolero Maxi Truck',
    status: 'Available',
    isPresent: true,
    clockInTime: '08:45 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Krone Service Station Hisar Hub',
    punchCoordinates: [29.1492, 75.7217],
    batteryLevel: 84,
    appVersion: 'Fieldy FSM v4.2.1',
    workingHours: 1.5,
    travelHours: 0.5,
    idleHours: 5.8,
    totalKm: 18.0,
    recentJobs: []
  },
  {
    id: 'TECH-12',
    name: 'Prem Kumar',
    role: 'Field Technician',
    region: 'Uttar Pradesh',
    phone: '+91 94120 88990',
    email: 'prem.kumar@krone.in',
    employeeCode: 'KIN-ENG-12',
    vehicleNumber: 'UP-12-ZZ-5501',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'Available',
    isPresent: true,
    clockInTime: '09:00 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Muzaffarnagar Field Support Center Base',
    punchCoordinates: [29.4727, 77.7085],
    batteryLevel: 89,
    appVersion: 'Fieldy FSM v4.2.1',
    workingHours: 2.0,
    travelHours: 0.6,
    idleHours: 5.0,
    totalKm: 22.0,
    recentJobs: []
  },
  {
    id: 'TECH-13',
    name: 'Kuldeep Gill',
    role: 'Field Technician',
    region: 'Punjab',
    phone: '+91 98142 99001',
    email: 'kuldeep.gill@krone.in',
    employeeCode: 'KIN-ENG-13',
    vehicleNumber: 'PB-10-PP-1122',
    vehicleModel: 'Depot Vehicle (Parked)',
    status: 'On Holiday/Leave',
    leaveType: 'Casual Leave (Approved)',
    isPresent: false,
    clockInTime: '—',
    clockOutTime: '—',
    punchLocationName: 'On Approved Leave (Expected Return: 2026-09-26)',
    punchCoordinates: [30.9010, 75.8573],
    batteryLevel: 0,
    appVersion: 'Offline',
    workingHours: 0.0,
    travelHours: 0.0,
    idleHours: 0.0,
    totalKm: 0.0,
    recentJobs: [
      { jobId: 'SR-26-0080', date: '2026-09-17', customer: 'Reliance Industries Ltd', machine: 'Krone BigPack 1290 HDP', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-14',
    name: 'Rohit Deshmukh',
    role: 'Apprentice Technician',
    region: 'Maharashtra',
    phone: '+91 98221 00112',
    email: 'rohit.deshmukh@krone.in',
    employeeCode: 'KIN-ENG-14',
    vehicleNumber: 'MH-12-XY-9988',
    vehicleModel: 'Depot Vehicle (Parked)',
    status: 'On Holiday/Leave',
    leaveType: 'Weekly Off',
    isPresent: false,
    clockInTime: '—',
    clockOutTime: '—',
    punchLocationName: 'Scheduled Weekly Off (Expected Return: 2026-09-26)',
    punchCoordinates: [18.1517, 74.5772],
    batteryLevel: 0,
    appVersion: 'Offline',
    workingHours: 0.0,
    travelHours: 0.0,
    idleHours: 0.0,
    totalKm: 0.0,
    recentJobs: []
  }
];
