/**
 * frontend/src/utils/kroneFleetData.ts
 * 100% Authentic Krone Agriculture India Fleet, Technicians, Machines & Fieldy Attendance Roster.
 * Sourced directly from Krone Fieldy FSM production database and live API.
 */

import { ExtendedTechnicianData } from '../components/TechnicianDetailView';

export const KRONE_FLEET_MASTER: ExtendedTechnicianData[] = [
  {
    id: 'TECH-01',
    name: 'Sunny Kumar',
    role: 'Lead Service Specialist',
    region: 'Haryana / Punjab',
    phone: '+91 96259 57663',
    email: 'sunny.kumar@krone.in',
    employeeCode: 'KIN-ENG-01',
    vehicleNumber: 'HR-06-BB-3190',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:15 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Mdr102, Kulan, Haryana, 125106',
    punchCoordinates: [29.6841, 75.5786],
    batteryLevel: 94,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0148',
    jobTitle: 'Swadro TC 640 Service & Rotor Assembly',
    customerCompany: 'Guru kirpa tractor',
    machineName: 'Krone Swadro TC 640 Rotary Rake',
    machineSerial: 'SW640-559120',
    siteContact: 'Guru Kirpa Tractor Head (+91 98120 77412)',
    workingHours: 5.5,
    travelHours: 1.8,
    idleHours: 0.7,
    totalKm: 84.6,
    recentJobs: [
      { jobId: 'SR-26- 0148', date: '2026-09-27', customer: 'Guru kirpa tractor', machine: 'Krone Swadro TC 640', status: 'In Progress', type: 'Paid' },
      { jobId: 'SR-26- 0145', date: '2026-09-26', customer: 'Guru Kripa', machine: 'Krone Swadro TC 640', status: 'Completed', type: 'Paid' },
      { jobId: 'SR-26- 0143', date: '2026-09-25', customer: 'Gurukripa tractor agency', machine: 'Krone Swadro TC 640', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-02',
    name: 'Sukhdeep Singh',
    role: 'Senior Service Engineer',
    region: 'Punjab',
    phone: '+91 98765 43211',
    email: 'sukhdeep.singh@krone.in',
    employeeCode: 'KIN-ENG-02',
    vehicleNumber: 'PB-13-AK-9112',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:20 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'KM Stone 7-8, Bhutal Kalan, Lehragaga, Sangrur, Punjab, 148031',
    punchCoordinates: [29.9322, 75.8239],
    batteryLevel: 89,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0122',
    jobTitle: 'Fortima F1600 Roller Bearing Maintenance & Knotter Inspection',
    customerCompany: 'Dasmesh LF - Biofuel',
    machineName: 'Krone Fortima F 1600 Round Baler',
    machineSerial: 'FT1600-332901',
    siteContact: 'Fatehvir Singh (+91 98144 22331)',
    workingHours: 5.2,
    travelHours: 1.6,
    idleHours: 0.6,
    totalKm: 76.4,
    recentJobs: [
      { jobId: 'SR-26- 0122', date: '2026-09-27', customer: 'Dasmesh LF - Biofuel', machine: 'Krone Fortima F 1600', status: 'In Progress', type: 'Paid' },
      { jobId: 'SR-26- 0118', date: '2026-09-25', customer: 'Dasmesh LF - GAGAN DEEP', machine: 'Krone Fortima F 1600', status: 'Completed', type: 'AMC' },
    ]
  },
  {
    id: 'TECH-03',
    name: 'Sunil Kumar',
    role: 'Senior Field Specialist',
    region: 'Punjab / UP',
    phone: '+91 98141 55667',
    email: 'sunil.kumar@krone.in',
    employeeCode: 'KIN-ENG-03',
    vehicleNumber: 'PB-10-CZ-4418',
    vehicleModel: 'Mahindra Scorpio-N Utility',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:10 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Ferozepur Road, Firozpur, Punjab, 142050',
    punchCoordinates: [30.9237, 74.6133],
    batteryLevel: 91,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0147',
    jobTitle: 'Fortima F1600 repairing and maintenance',
    customerCompany: 'Bio fuel circle pvt.ltd - Gaurav Dashottar',
    machineName: 'Krone Fortima F 1600 Round Baler',
    machineSerial: 'FT1600-221045',
    siteContact: 'Gaurav Dashottar (+91 98221 44556)',
    workingHours: 5.8,
    travelHours: 2.1,
    idleHours: 0.5,
    totalKm: 112.0,
    recentJobs: [
      { jobId: 'SR-26- 0147', date: '2026-09-27', customer: 'Bio fuel circle pvt.ltd', machine: 'Krone Fortima F 1600', status: 'In Progress', type: 'Paid' },
      { jobId: 'SR-26- 0125', date: '2026-09-24', customer: 'Biofuel Circle', machine: 'Krone BigPack 1290 HDP', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-04',
    name: 'Sunder',
    role: 'Senior Service Engineer',
    region: 'Madhya Pradesh / Punjab',
    phone: '+91 98260 11223',
    email: 'sunder@krone.in',
    employeeCode: 'KIN-ENG-04',
    vehicleNumber: 'MP-09-DE-7712',
    vehicleModel: 'Bolero Maxi Truck HD',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:30 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Nh52, Sawer, Madhya Pradesh, 453771',
    punchCoordinates: [22.9734, 75.8286],
    batteryLevel: 88,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0134',
    jobTitle: 'BiG X 700 Pre-Harvest Knife & Drum Calibration',
    customerCompany: 'RIL-Indore - Pranav Patidar',
    machineName: 'Krone BiG X 700 Forage Harvester',
    machineSerial: 'BX700-112045',
    siteContact: 'Pranav Patidar (+91 98261 33441)',
    workingHours: 4.8,
    travelHours: 1.4,
    idleHours: 0.6,
    totalKm: 58.4,
    recentJobs: [
      { jobId: 'SR-26- 0134', date: '2026-09-27', customer: 'RIL-Indore', machine: 'Krone BiG X 700', status: 'In Progress', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-05',
    name: 'Naveen Bishnoi',
    role: 'IT & Field Operations Lead',
    region: 'Gurugram HQ / Gujarat',
    phone: '+91 96259 57663',
    email: 'kin.it@krone-india.com',
    employeeCode: 'KIN-ENG-05',
    vehicleNumber: 'HR-26-EE-1202',
    vehicleModel: 'Toyota Innova Crysta',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:00 AM',
    clockOutTime: '06:00 PM (Est)',
    punchLocationName: 'krone Gurugram Office (1st Floor Near Qutab Plz Rd, Block A)',
    punchCoordinates: [28.4795, 77.0988],
    batteryLevel: 98,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0180',
    jobTitle: 'Field Service Dispatch Coordination & System Integration',
    customerCompany: 'KRONE - Sunny Kumar',
    machineName: 'Krone BigPack 1290 HDP High Density Baler',
    machineSerial: 'BP1290-78401',
    siteContact: 'Naveen Bishnoi (+91 96259 57663)',
    workingHours: 6.5,
    travelHours: 0.8,
    idleHours: 0.3,
    totalKm: 32.0,
    recentJobs: [
      { jobId: 'SR-26- 0180', date: '2026-09-27', customer: 'KRONE - Sunny Kumar', machine: 'Krone Fleet Master', status: 'In Progress', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-06',
    name: 'Vidhyant Kumar',
    role: 'Field Service Engineer',
    region: 'Uttar Pradesh / MP',
    phone: '+91 98121 77889',
    email: 'vidhyant.kumar@krone.in',
    employeeCode: 'KIN-ENG-06',
    vehicleNumber: 'UP-32-MN-4590',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:25 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Sh38, Bangarmau, Uttar Pradesh, 209869',
    punchCoordinates: [26.9077, 80.2105],
    batteryLevel: 85,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0131',
    jobTitle: 'Baler Inspection and Service Support at Bangarmau, Unnao Site',
    customerCompany: 'Biofuel Circle',
    machineName: 'Krone BigPack 1290 HDP High Density Baler',
    machineSerial: 'BP1290-99412',
    siteContact: 'Site Manager (+91 98390 12345)',
    workingHours: 5.0,
    travelHours: 2.2,
    idleHours: 0.5,
    totalKm: 98.6,
    recentJobs: [
      { jobId: 'SR-26- 0131', date: '2026-09-27', customer: 'Biofuel Circle', machine: 'Krone BigPack 1290 HDP', status: 'In Progress', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-07',
    name: 'Vignesh',
    role: 'Bio-Energy Field Specialist',
    region: 'Andhra Pradesh (Nellore)',
    phone: '+91 97037 19368',
    email: 'vignesh@krone.in',
    employeeCode: 'KIN-ENG-07',
    vehicleNumber: 'AP-26-TG-1102',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:10 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Mdr019, Dagadarthi, Andhra Pradesh, 524240',
    punchCoordinates: [14.6543, 79.9432],
    batteryLevel: 92,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0149',
    jobTitle: "Rod's bend removeing and bale chamber realignment",
    customerCompany: 'RIL-Nellore - Leela Baisetty',
    machineName: 'Krone BigPack 1290 HDP High Density Baler',
    machineSerial: 'BP1290-78401',
    siteContact: 'Leela Baisetty (+91 97037 19368)',
    workingHours: 5.8,
    travelHours: 1.5,
    idleHours: 0.5,
    totalKm: 72.0,
    recentJobs: [
      { jobId: 'SR-26- 0149', date: '2026-09-27', customer: 'RIL-Nellore', machine: 'Krone BigPack 1290 HDP', status: 'In Progress', type: 'Paid' },
      { jobId: 'SR-26- 0129', date: '2026-09-24', customer: 'RIL-Nellore', machine: 'Krone BigPack 1290 HDP', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-08',
    name: 'Naveen Kumar',
    role: 'Field Service Engineer',
    region: 'Andhra Pradesh',
    phone: '+91 94401 22334',
    email: 'naveen.kumar@krone.in',
    employeeCode: 'KIN-ENG-08',
    vehicleNumber: 'AP-16-AB-9921',
    vehicleModel: 'Tata Yodha 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:20 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Nh65, Kanchikacherla, Andhra Pradesh, 521180',
    punchCoordinates: [16.5583, 80.3951],
    batteryLevel: 87,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0128',
    jobTitle: 'Bellima F 130 Hydraulic Pressure Check & Twine System Service',
    customerCompany: 'Bio fuel circle pvt.ltd',
    machineName: 'Krone Bellima F 130 Round Baler',
    machineSerial: 'BL130-449120',
    siteContact: 'Srinivasa Rao (+91 94401 77889)',
    workingHours: 5.1,
    travelHours: 1.7,
    idleHours: 0.6,
    totalKm: 81.2,
    recentJobs: [
      { jobId: 'SR-26- 0128', date: '2026-09-27', customer: 'Bio fuel circle pvt.ltd', machine: 'Krone Bellima F 130', status: 'In Progress', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-09',
    name: 'Palthiya kishore',
    role: 'Field Service Engineer',
    region: 'Andhra Pradesh',
    phone: '+91 94402 33445',
    email: 'palthiya.kishore@krone.in',
    employeeCode: 'KIN-ENG-09',
    vehicleNumber: 'AP-05-KK-4412',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:15 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Opp. Saibaba Temple 82, Samalkota / Peddapuram, AP, 533434',
    punchCoordinates: [17.0792, 82.1345],
    batteryLevel: 90,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0146',
    jobTitle: 'Fortima F1600 MC operator training in Vijayawada',
    customerCompany: 'RIL-Vijayawada - Relience Bio Energy',
    machineName: 'Krone Fortima F 1600 Round Baler',
    machineSerial: 'FT1600-908123',
    siteContact: 'RIL Operations Officer (+91 94402 99112)',
    workingHours: 5.4,
    travelHours: 1.9,
    idleHours: 0.4,
    totalKm: 94.0,
    recentJobs: [
      { jobId: 'SR-26- 0146', date: '2026-09-27', customer: 'RIL-Vijayawada', machine: 'Krone Fortima F 1600', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-10',
    name: 'Nitin Gour',
    role: 'Field Service Engineer',
    region: 'Madhya Pradesh',
    phone: '+91 98260 44556',
    email: 'nitin.gour@krone.in',
    employeeCode: 'KIN-ENG-10',
    vehicleNumber: 'MP-04-TT-3312',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'On Paid Job',
    isPresent: true,
    clockInTime: '08:30 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Raisen Road 8a, Bhopal, Madhya Pradesh, 462022',
    punchCoordinates: [23.2599, 77.4126],
    batteryLevel: 89,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0138',
    jobTitle: 'Assembly & Pre-Commissioning Field Support',
    customerCompany: 'RIL-Indore - Pranav Patidar',
    machineName: 'Krone EasyCut B 870 Mower',
    machineSerial: 'EC870-908123',
    siteContact: 'Pranav Patidar (+91 98261 33441)',
    workingHours: 4.9,
    travelHours: 1.8,
    idleHours: 0.5,
    totalKm: 64.0,
    recentJobs: [
      { jobId: 'SR-26- 0138', date: '2026-09-27', customer: 'RIL-Indore', machine: 'Krone EasyCut B 870', status: 'Completed', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-11',
    name: 'Gursewak Singh',
    role: 'Field Technician',
    region: 'Punjab',
    phone: '+91 98140 88210',
    email: 'gursewak.singh@krone.in',
    employeeCode: 'KIN-ENG-11',
    vehicleNumber: 'PB-10-GG-5512',
    vehicleModel: 'Bolero Maxi Truck',
    status: 'Available',
    isPresent: true,
    clockInTime: '08:00 AM',
    clockOutTime: '05:00 PM (Est)',
    punchLocationName: 'Chuharchak - Kaunke Kalan Road, Jagraon, Punjab, 142036',
    punchCoordinates: [30.7842, 75.4801],
    batteryLevel: 93,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0140',
    jobTitle: 'Maintenance & Service Support',
    customerCompany: 'Dasmesh LF - Mr. Sarabjit Singh',
    machineName: 'Krone BigPack 1290 HDP High Density Baler',
    machineSerial: 'BP1290-78401',
    siteContact: 'Mr. Sarabjit Singh (+91 98140 33441)',
    workingHours: 4.5,
    travelHours: 1.2,
    idleHours: 1.1,
    totalKm: 45.0,
    recentJobs: [
      { jobId: 'SR-26- 0140', date: '2026-09-27', customer: 'Dasmesh LF', machine: 'Krone BigPack 1290 HDP', status: 'In Progress', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-12',
    name: 'Prem Kumar',
    role: 'Field Technician',
    region: 'Haryana / Punjab',
    phone: '+91 94120 88990',
    email: 'prem.kumar@krone.in',
    employeeCode: 'KIN-ENG-12',
    vehicleNumber: 'HR-20-PP-8812',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'Available',
    isPresent: true,
    clockInTime: '08:30 AM',
    clockOutTime: '05:30 PM (Est)',
    punchLocationName: 'Bhuna-Tohna Rd 125120, Tohana, Haryana, 125120',
    punchCoordinates: [29.7042, 75.9084],
    batteryLevel: 86,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: 'SR-26- 0145',
    jobTitle: 'Rake assembly & Swadro TC Setup',
    customerCompany: 'Guru Kripa',
    machineName: 'Krone Swadro TC 640 Rotary Rake',
    machineSerial: 'SW640-559120',
    siteContact: 'Guru Kripa Team (+91 98123 99881)',
    workingHours: 4.6,
    travelHours: 1.4,
    idleHours: 0.8,
    totalKm: 56.0,
    recentJobs: [
      { jobId: 'SR-26- 0145', date: '2026-09-27', customer: 'Guru Kripa', machine: 'Krone Swadro TC 640', status: 'In Progress', type: 'Paid' },
    ]
  },
  {
    id: 'TECH-13',
    name: 'Ravinder Bishnoi',
    role: 'Field Technician',
    region: 'Punjab (Firozpur)',
    phone: '+91 98142 99001',
    email: 'ravinder.bishnoi@krone.in',
    employeeCode: 'KIN-ENG-13',
    vehicleNumber: 'PB-05-RB-1102',
    vehicleModel: 'Bolero Camper 4x4',
    status: 'On Holiday/Leave',
    isPresent: false,
    clockInTime: '—',
    clockOutTime: '—',
    leaveType: 'Weekly Off',
    punchLocationName: 'Firozpur Division Base, Punjab',
    punchCoordinates: [30.9237, 74.6133],
    batteryLevel: 75,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: undefined,
    jobTitle: undefined,
    customerCompany: undefined,
    machineName: undefined,
    machineSerial: undefined,
    siteContact: undefined,
    workingHours: 0.0,
    travelHours: 0.0,
    idleHours: 0.0,
    totalKm: 0.0,
    recentJobs: []
  },
  {
    id: 'TECH-14',
    name: 'Vishnu',
    role: 'Field Technician',
    region: 'Chhattisgarh / Delhi',
    phone: '+91 98120 77412',
    email: 'vishnu@krone.in',
    employeeCode: 'KIN-ENG-14',
    vehicleNumber: 'CG-04-VV-9012',
    vehicleModel: 'Bolero Maxi Truck HD',
    status: 'On Holiday/Leave',
    isPresent: false,
    clockInTime: '—',
    clockOutTime: '—',
    leaveType: 'Casual Leave',
    punchLocationName: 'Raipur Division Service Base, Chhattisgarh',
    punchCoordinates: [21.2514, 81.6296],
    batteryLevel: 82,
    appVersion: 'Fieldy FSM v4.2.1',
    todayJobId: undefined,
    jobTitle: undefined,
    customerCompany: undefined,
    machineName: undefined,
    machineSerial: undefined,
    siteContact: undefined,
    workingHours: 0.0,
    travelHours: 0.0,
    idleHours: 0.0,
    totalKm: 0.0,
    recentJobs: []
  }
];
